version: "3"

services:
  # PHP-FPM
  php-fpm:
    build:
      context: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ../freelancing/:/var/www
    extra_hosts:
      - "smart.local:172.19.0.4"

  # Web Server
  web:
    build:
      context: ./nginx
    working_dir: /var/www
    volumes:
      - ../freelancing/:/var/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  # Maria DB
  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Mailhog
  mailhog:
    build:
      context: ./mailhog/
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mariadb_data:
